services:
  - type: web
    runtime: node
    name: silent-auction-backend
    buildCommand: cd silent-auction-backend && npm install
    startCommand: cd silent-auction-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false # This will be set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true # Render will generate a secure random value
