services:
  - type: web
    runtime: node
    name: silent-auction-backend
    rootDir: silent-auction-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # This will be set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true # Render will generate a secure random value
